Budget App
iamchristianani/budget-app pull request #9
Opened 2023-04-27 19:52 UTC by iamchristianani

## Budget App || Ruby on Rails Capstone Project

### Hello Code Reviewer

#### Video Presentation: [Link](https://www.loom.com/share/76ca96e7229f4800aa389e397c523c7b)
#### Live Demo: [Link](https://bill-splitter-v1fd.onrender.com/)

> In this Pull Request, the following changes were made

- [x] Added the splash screen.
- [x] Added the Signup and Log-in pages.
- [x] Added Group (Categories) page.
- [x] Added Expenses (Transaction) page.
- [x] Added the "Add a new group" form page.
- [x] Added the "Add a new expense" form page.
- [x] Added unit test using RSpec.
- [x] Ensured the database table matches the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/images/erd_diagram.png) diagram.
- [x] Ensured there was no linter error.
- [x] Deployed the app using [render](https://bill-splitter-v1fd.onrender.com/).
- [x] Updated my readme file.

2023-04-27 20:33 UTC, addod19 commented
### Hi @iamchristianani, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the README file is missing the `future features` section

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-27 22:22 UTC, Lucas-Masaba requested changes
# Hello @iamchristianani  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks are passing :heavy_check_mark: 
- Tests are passing :heavy_check_mark: 
- The UI is generally good-looking:star: 
- Descriptive README :scroll: 
- Descriptive pull request :writing_hand: 
- Meaningful commit messages :surfer: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 22:22 UTC, Lucas-Masaba commented on app/views/groups/index.html.erb
> +  <%= link_to 'Add a new group', new_group_path, class: 'btn bg-sec w-100 text-light' %>
- [ ] Please make sure this button looks similar like that provided in the original design. It should be at the bottom of the page with a white thin border surrounding the test.
### Your Implementation
![image](https://user-images.githubusercontent.com/45460192/235000984-cce38f49-672a-4c8b-9699-2ae6d062307b.png)
### Required
![image](https://user-images.githubusercontent.com/45460192/235001100-accf13b9-bba3-4114-aa84-7486189531db.png)

As mentioned in the project requirements, you should follow all the [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:

* Colors
* Typography: font face, size and weight.
* Layout: composition and space between elements

2023-04-27 22:22 UTC, Lucas-Masaba commented on app/views/expenses/index.html.erb
> +  <%= link_to 'Add a new Expense', new_expense_path, class: 'btn bg-sec w-100 text-light' %>
- [ ] Please make sure this button looks similar to that provided in the original design. It should be at the bottom of the page with a thin white border surrounding the test like I mentioned in the previous comment

2023-04-28 10:48 UTC, julie-ify approved these changes
Hi @iamchristianani,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 10:52 UTC, merged